import os
import smtplib
from email.mime.multipart import MIMEMultipart
from email.mime.text import MIMEText
import pandas as pd
import datetime

# --- CONFIG ---
SCRIPT_DIR = os.path.dirname(os.path.abspath(__file__))
SIGNALS_FILE = os.path.join(SCRIPT_DIR, "signals", "signals.csv")

# Environment variables for email credentials
SMTP_SERVER = os.environ.get("SMTP_SERVER", "smtp.office365.com")
SMTP_PORT = int(os.environ.get("SMTP_PORT", 587))
SMTP_USER = os.environ.get("SMTP_USER", "")
SMTP_PASS = os.environ.get("SMTP_PASS", "")
EMAIL_TO = os.environ.get("EMAIL_TO", "ben.lefort@ofa.on.ca")

def generate_morning_briefing():
    print("--- Generating Morning Intelligence Briefing ---")
    
    if not os.path.exists(SIGNALS_FILE):
        print("No signals file found to report on.")
        return

    df = pd.read_csv(SIGNALS_FILE)
    
    # Filter to only show AI-verified hits with high confidence (e.g., > 50) from the last 24 hours
    if 'ai_confidence' in df.columns:
        df = df[df['ai_confidence'] >= 50]
        
    # Filter to recent (last 7 days since this runs weekly)
    today = datetime.datetime.now()
    seven_days_ago = today - datetime.timedelta(days=7)
    
    if 'discovered_date' in df.columns:
        df['discovered_date'] = pd.to_datetime(df['discovered_date'])
        df = df[df['discovered_date'] >= seven_days_ago]

    if df.empty:
        print("No new verified AI hits in the last 48 hours. No email sent.")
        return

    print(f"Found {len(df)} new AI-verified hits. Preparing email...")

    # Build HTML Email
    html_content = f"""
    <html>
      <body style="font-family: Arial, sans-serif; color: #333;">
        <h2 style="color: #2c3e50;">🔎 OFA Municipal Intelligence: Morning Briefing</h2>
        <p>Your overnight AI scanner has completed its run. Here are the most recent verified bylaw developments:</p>
        <hr style="border: 1px solid #eee;">
    """

    for _, row in df.iterrows():
        name = row.get('munid', 'Unknown Municipality')
        category = row.get('category', 'Unknown')
        snippet = row.get('ai_summary', row.get('snippet', 'No summary available.'))
        url = row.get('evidence_url', '#')
        
        html_content += f"""
        <div style="margin-bottom: 20px; padding: 15px; border-left: 4px solid #3498db; background-color: #f9f9f9;">
            <h3 style="margin-top: 0; color: #2980b9;">{name} - {category}</h3>
            <p style="font-size: 14px; line-height: 1.5;">{snippet}</p>
            <a href="{url}" style="color: #e67e22; text-decoration: none; font-weight: bold;">[View Source Document]</a>
        </div>
        """

    html_content += """
        <p style="font-size: 12px; color: #7f8c8d; margin-top: 30px;">
            This is an automated report generated by the Ontario Federation of Agriculture's AI Intelligence Scanner.
        </p>
      </body>
    </html>
    """

    if not SMTP_USER or not SMTP_PASS:
        print("Skipping SMTP send (No credentials configured). Saving to disk instead.")
        with open(os.path.join(SCRIPT_DIR, "signals", "morning_briefing_draft.html"), "w", encoding='utf-8') as f:
            f.write(html_content)
        return

    # Send Email
    try:
        msg = MIMEMultipart('alternative')
        msg['Subject'] = f"OFA Intelligence Briefing: {len(df)} New Bylaw Actions"
        msg['From'] = SMTP_USER
        msg['To'] = EMAIL_TO

        msg.attach(MIMEText(html_content, 'html'))

        server = smtplib.SMTP(SMTP_SERVER, SMTP_PORT)
        server.starttls()
        server.login(SMTP_USER, SMTP_PASS)
        server.sendmail(SMTP_USER, EMAIL_TO.split(','), msg.as_string())
        server.quit()
        print("Morning Briefing email sent successfully.")
    except Exception as e:
        print(f"Failed to send email: {e}")

if __name__ == "__main__":
    generate_morning_briefing()
